name: Security check - Bandit

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Start Measurement
      uses: green-coding-solutions/eco-ci-energy-estimation@v4 # use hash or @vX here (See note below)
      with:
        task: start-measurement

    - uses: actions/checkout@v4

    - name: Security check - Bandit
      uses: ioggstream/bandit-report-artifacts@v1.7.4
      with:
        project_path: src
        # ignore_failure: true

    # This is optional
    #- name: Security check report artifacts
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: Security report
    #    path: output/security_report.txt

    - name: Tests measurement
      uses: green-coding-solutions/eco-ci-energy-estimation@v4 # use hash or @vX here (See note below)
      with:
        task: get-measurement
        label: 'pytest'
      # continue-on-error: true # recommended setting for production. See notes below.

    - name: Show Energy Results
      uses: green-coding-solutions/eco-ci-energy-estimation@v4 # use hash or @vX here (See note below)
      with:
        task: display-results
      # continue-on-error: true # recommended setting for production. See notes below.