# -*- coding: utf-8 -*-
CUSTOM = {
    "allowedRolesAndUsers": 80,
    "effectiveRange": 100,
}


def rank_index(index, query):
    if (
        index == "UID"
        and isinstance(query.get("UID"), dict)  # noqa
        and query["UID"].get("not")  # noqa
    ):
        return 100
    return CUSTOM.get(index, 0)


def Catalog_sorted_search_indexes(self, query):
    return sorted(
        self._orig_sorted_search_indexes(query), key=lambda i: (rank_index(i, query), i)
    )


# query plan dumped at 'Wed Aug  3 23:57:09 2022' gdfstatging
queryplan = {
    ("", "Plone", "portal_catalog"): {
        "VALUE_INDEXES": frozenset(
            {
                "destinatari_bando",
                "cognome_dirigente",
                "apertura_bando",
                "in_reply_to",
                "event_location",
                "getRawRelatedItems",
                "ente_bando",
                "data_conclusione_incarico",
                "meta_type",
                "commentators",
                "service_venue",
                "news_uo",
                "grado_dirigente",
                "is_default_page",
                "tipologia_bando",
                "tipologia_organizzazione",
                "tassonomia_argomenti",
                "tipologia_documento",
                "Language",
                "ordine_dirigente",
                "sync_uid",
                "news_people",
                "uo_location",
                "is_folderish",
                "expires",
                "review_state",
                "total_comments",
                "news_service",
                "exclude_from_nav",
                "news_venue",
            }
        ),
        (
            "allowedRolesAndUsers",
            "effectiveRange",
            "path",
            "portal_type",
            "sort_on",
            "sort_order",
            ("exclude_from_nav", "False"),
            ("is_default_page", "False"),
            ("is_folderish", "True"),
        ): {
            "allowedRolesAndUsers": (0.0098, 1, True),
            "allowedRolesAndUsers#intersection": (0.0097, 1, False),
            "effectiveRange": (0.0007, 1, True),
            "effectiveRange#intersection": (0.0, 1, False),
            "exclude_from_nav": (0.0103, 1, True),
            "exclude_from_nav#intersection": (0.0, 1, False),
            "is_default_page": (0.0082, 1, True),
            "is_default_page#intersection": (0.0, 1, False),
            "is_folderish": (0.0052, 1, True),
            "is_folderish#intersection": (0.0, 1, False),
            "path": (0.0009, 1, True),
            "path#intersection": (0.0008, 1, False),
            "portal_type": (0.0102, 1, True),
            "portal_type#intersection": (0.0, 1, False),
            "sort_on": (0, 0, False),
            "sort_order": (0, 0, False),
        },
        (
            "allowedRolesAndUsers",
            "effectiveRange",
            "path",
            "portal_type",
            "sort_on",
            ("Language", "'it'"),
            ("exclude_from_nav", "False"),
            ("is_default_page", "False"),
            ("is_folderish", "True"),
        ): {
            "Language": (0.007, 1, True),
            "Language#intersection": (0.0069, 1, False),
            "allowedRolesAndUsers": (0.0075, 1, True),
            "allowedRolesAndUsers#intersection": (0.0074, 1, False),
            "effectiveRange": (0.0001, 1, True),
            "effectiveRange#intersection": (0.0, 1, False),
            "exclude_from_nav": (0.0088, 1, True),
            "exclude_from_nav#intersection": (0.0, 1, False),
            "is_default_page": (0.0085, 1, True),
            "is_default_page#intersection": (0.0, 1, False),
            "is_folderish": (0.0047, 1, True),
            "is_folderish#intersection": (0.0, 1, False),
            "path": (0.0001, 1, True),
            "path#intersection": (0.0, 1, False),
            "portal_type": (0.0008, 1, True),
            "portal_type#intersection": (0.0008, 1, False),
            "sort_on": (0, 0, False),
        },
        ("TranslationGroup", "allowedRolesAndUsers", "show_inactive"): {
            "TranslationGroup": (0.0019, 1, True),
            "TranslationGroup#intersection": (0.0, 1, False),
            "allowedRolesAndUsers": (0.0064, 1, True),
            "allowedRolesAndUsers#intersection": (0.0, 1, False),
            "show_inactive": (0, 0, False),
        },
        (
            "UID",
            "allowedRolesAndUsers",
            "path",
            "portal_type",
            "sort_limit",
            "sort_on",
            "sort_order",
            ("review_state", "{'query': ['published']}"),
        ): {
            "UID": (0.0002, 1, True),
            "UID#intersection": (0.0, 1, False),
            "allowedRolesAndUsers": (0.0294, 1, True),
            "allowedRolesAndUsers#intersection": (0.0016, 1, False),
            "path": (0.0375, 1, True),
            "path#intersection": (0.0, 1, False),
            "portal_type": (0.0002, 1, True),
            "portal_type#intersection": (0.0, 1, False),
            "review_state": (0.0178, 1, True),
            "review_state#intersection": (0.0177, 1, False),
            "sort_limit": (0, 0, False),
            "sort_on": (0, 0, False),
            "sort_order": (0, 0, False),
        },
        (
            "UID",
            "allowedRolesAndUsers",
            "path",
            "portal_type",
            "sort_limit",
            "sort_on",
            "sort_order",
        ): {
            "UID": (0.0002, 1, True),
            "UID#intersection": (0.0, 1, False),
            "allowedRolesAndUsers": (0.0098, 1, True),
            "allowedRolesAndUsers#intersection": (0.0, 1, False),
            "path": (0.0137, 1, True),
            "path#intersection": (0.0, 1, False),
            "portal_type": (0.0002, 1, True),
            "portal_type#intersection": (0.0, 1, False),
            "sort_limit": (0, 0, False),
            "sort_on": (0, 0, False),
            "sort_order": (0, 0, False),
        },
        ("UID",): {
            "UID": (0.0001, 1, True),
            "UID#intersection": (0.0, 1, False),
        },
        ("allowedRolesAndUsers", "path", "sort_on"): {
            "allowedRolesAndUsers": (0.0085, 1, True),
            "allowedRolesAndUsers#intersection": (0.0, 1, False),
            "path": (0.0034, 1, True),
            "path#intersection": (0.0, 1, False),
            "sort_on": (0, 0, False),
        },
        (
            "UID",
            "allowedRolesAndUsers",
            "effectiveRange",
            "path",
            "portal_type",
            "sort_limit",
            "sort_on",
            "sort_order",
        ): {
            "UID": (0.0002, 1, True),
            "UID#intersection": (0.0, 1, False),
            "allowedRolesAndUsers": (0.009, 1, True),
            "allowedRolesAndUsers#intersection": (0.0089, 1, False),
            "effectiveRange": (0.0016, 1, True),
            "effectiveRange#intersection": (0.0, 1, False),
            "path": (0.0281, 1, True),
            "path#intersection": (0.0, 1, False),
            "portal_type": (0.0002, 1, True),
            "portal_type#intersection": (0.0, 1, False),
            "sort_limit": (0, 0, False),
            "sort_on": (0, 0, False),
            "sort_order": (0, 0, False),
        },
        (
            "UID",
            "allowedRolesAndUsers",
            "effectiveRange",
            "path",
            "portal_type",
            "sort_limit",
            "sort_on",
            "sort_order",
            ("review_state", "{'query': ['published']}"),
        ): {
            "UID": (0.0002, 1, True),
            "UID#intersection": (0.0, 1, False),
            "allowedRolesAndUsers": (0.0317, 1, True),
            "allowedRolesAndUsers#intersection": (0.0315, 1, False),
            "effectiveRange": (0.0004, 1, True),
            "effectiveRange#intersection": (0.0, 1, False),
            "path": (0.0429, 1, True),
            "path#intersection": (0.0, 1, False),
            "portal_type": (0.0001, 1, True),
            "portal_type#intersection": (0.0, 1, False),
            "review_state": (0.0044, 1, True),
            "review_state#intersection": (0.0044, 1, False),
            "sort_limit": (0, 0, False),
            "sort_on": (0, 0, False),
            "sort_order": (0, 0, False),
        },
        ("allowedRolesAndUsers", "effectiveRange", "portal_type"): {
            "allowedRolesAndUsers": (0.0071, 1, True),
            "allowedRolesAndUsers#intersection": (0.007, 1, False),
            "effectiveRange": (0.0008, 1, True),
            "effectiveRange#intersection": (0.0, 1, False),
            "portal_type": (0.0001, 1, True),
            "portal_type#intersection": (0.0, 1, False),
        },
        ("allowedRolesAndUsers", "portal_type"): {
            "allowedRolesAndUsers": (0.0093, 1, True),
            "allowedRolesAndUsers#intersection": (0.0, 1, False),
            "portal_type": (0.0001, 1, True),
            "portal_type#intersection": (0.0, 1, False),
        },
        ("allowedRolesAndUsers", "effectiveRange", "path", "sort_on"): {
            "allowedRolesAndUsers": (0.008, 1, True),
            "allowedRolesAndUsers#intersection": (0.008, 1, False),
            "effectiveRange": (0.0003, 1, True),
            "effectiveRange#intersection": (0.0, 1, False),
            "path": (0.0001, 1, True),
            "path#intersection": (0.0, 1, False),
            "sort_on": (0, 0, False),
        },
        (
            "UID",
            "allowedRolesAndUsers",
            "effectiveRange",
            "path",
            "sort_limit",
            "sort_on",
            "sort_order",
        ): {
            "UID": (0.0004, 1, True),
            "UID#intersection": (0.0, 1, False),
            "allowedRolesAndUsers": (0.0041, 1, True),
            "allowedRolesAndUsers#intersection": (0.004, 1, False),
            "effectiveRange": (0.0003, 1, True),
            "effectiveRange#intersection": (0.0, 1, False),
            "path": (0.0202, 1, True),
            "path#intersection": (0.0, 1, False),
            "sort_limit": (0, 0, False),
            "sort_on": (0, 0, False),
            "sort_order": (0, 0, False),
        },
        (
            "UID",
            "allowedRolesAndUsers",
            "path",
            "portal_type",
            "reparti_correlati",
            "sort_limit",
            "sort_on",
            "sort_order",
            ("review_state", "{'query': ['published']}"),
        ): {
            "UID": (0.0002, 1, True),
            "UID#intersection": (0.0, 1, False),
            "allowedRolesAndUsers": (0.0297, 1, True),
            "allowedRolesAndUsers#intersection": (0.0, 1, False),
            "path": (0.0285, 1, True),
            "path#intersection": (0.0, 1, False),
            "portal_type": (0.0002, 1, True),
            "portal_type#intersection": (0.0, 1, False),
            "reparti_correlati": (0.0003, 1, True),
            "reparti_correlati#intersection": (0.0002, 1, False),
            "review_state": (0.0231, 1, True),
            "review_state#intersection": (0.023, 1, False),
            "sort_limit": (0, 0, False),
            "sort_on": (0, 0, False),
            "sort_order": (0, 0, False),
        },
        ("UID", "allowedRolesAndUsers", "path", "sort_limit"): {
            "UID": (0.0005, 1, True),
            "UID#intersection": (0.0, 1, False),
            "allowedRolesAndUsers": (0.0122, 1, True),
            "allowedRolesAndUsers#intersection": (0.0, 1, False),
            "path": (0.002, 1, True),
            "path#intersection": (0.0, 1, False),
            "sort_limit": (0, 0, False),
        },
        (
            "UID",
            "allowedRolesAndUsers",
            "effective",
            "path",
            "portal_type",
            "reparti_correlati",
            "sort_limit",
            "sort_on",
            "sort_order",
        ): {
            "UID": (0.0658, 1, True),
            "UID#intersection": (0.0, 1, False),
            "allowedRolesAndUsers": (0.0188, 1, True),
            "allowedRolesAndUsers#intersection": (0.0, 1, False),
            "effective": (9.9603, 1, True),
            "effective#intersection": (0.0004, 1, False),
            "path": (0.053, 1, True),
            "path#intersection": (0.0528, 1, False),
            "portal_type": (0.0001, 1, True),
            "portal_type#intersection": (0.0, 1, False),
            "reparti_correlati": (0.0012, 1, True),
            "reparti_correlati#intersection": (0.0, 1, False),
            "sort_limit": (0, 0, False),
            "sort_on": (0, 0, False),
            "sort_order": (0, 0, False),
        },
        (
            "UID",
            "allowedRolesAndUsers",
            "effective",
            "effectiveRange",
            "path",
            "portal_type",
            "reparti_correlati",
            "sort_limit",
            "sort_on",
            "sort_order",
        ): {
            "UID": (0.0003, 1, True),
            "UID#intersection": (0.0, 1, False),
            "allowedRolesAndUsers": (0.0203, 1, True),
            "allowedRolesAndUsers#intersection": (0.0202, 1, False),
            "effective": (0.0225, 1, True),
            "effective#intersection": (0.0003, 1, False),
            "effectiveRange": (0.0008, 1, True),
            "effectiveRange#intersection": (0.0, 1, False),
            "path": (0.0152, 1, True),
            "path#intersection": (0.015, 1, False),
            "portal_type": (0.0003, 1, True),
            "portal_type#intersection": (0.0002, 1, False),
            "reparti_correlati": (0.0004, 1, True),
            "reparti_correlati#intersection": (0.0, 1, False),
            "sort_limit": (0, 0, False),
            "sort_on": (0, 0, False),
            "sort_order": (0, 0, False),
        },
    },
}
